name: Components

#on:
#  workflow_call:

on: [push, pull_request]

env:
  BuidlDir: buildDir
  CC: /usr/bin/clang-18
  CXX: /usr/bin/clang++-18

jobs:
  debug:
    uses: ./.github/workflows/template.yaml
    with:
      build_type: 'debug'
      extra_args: ''
      target: 'components'

  debug-sanitize-address:
    uses: ./.github/workflows/template.yaml
    with:
      build_type: 'debug'
      extra_args: '-Db_sanitize=address -Db_lundef=false'
      target: 'components'

  debug-sanitize-leak:
    uses: ./.github/workflows/template.yaml
    with:
      build_type: 'debug'
      extra_args: '-Db_sanitize=leak -Db_lundef=false'
      target: 'components'

  debug-sanitize-thread:
    uses: ./.github/workflows/template.yaml
    with:
      build_type: 'debug'
      extra_args: '-Db_sanitize=thread -Db_lundef=false'
      target: 'components'

  debug-sanitize-undefined:
    uses: ./.github/workflows/template.yaml
    with:
      build_type: 'debug'
      extra_args: '-Db_sanitize=undefined -Db_lundef=false'
      target: 'components'

  release:
    uses: ./.github/workflows/template.yaml
    with:
      build_type: 'release'
      extra_args: ''
      target: 'components'