name: Executor

on:
  workflow_call:

env:
  CLANG_15: clang++-16

jobs:
  ubuntu-clang-16:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}-executor
      - run: |
          python tools/prepare.py
      - run: |
               meson setup --native-file buildDir/conan_meson_native.ini buildDir .
               meson compile -C buildDir
               meson test -C buildDir


