name: Target build types

on:
  workflow_call:
    inputs:
      target:
        description: 'Target for Meson'
        required: true
        type: string

env:
  CC: /usr/bin/clang-18
  CXX: /usr/bin/clang++-18

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - name: 'Debug'
            build_type: 'debug'
            extra_args: ''
            target: ${{ inputs.target }}
            buildDir: 'buildDirDebug'
          - name: 'Debug with address sanitize'
            build_type: 'debug'
            extra_args: '-Db_sanitize=address -Db_lundef=false'
            target: ${{ inputs.target }}
            buildDir: 'buildDirDebugAsan'
          - name: 'Debug with leak sanitize'
            build_type: 'debug'
            extra_args: '-Db_sanitize=leak -Db_lundef=false'
            target: ${{ inputs.target }}
            buildDir: 'buildDirDebugLsan'
          - name: 'Debug with thread sanitize'
            build_type: 'debug'
            extra_args: '-Db_sanitize=thread -Db_lundef=false'
            target: ${{ inputs.target }}
            buildDir: 'buildDirDebugTsan'
          - name: 'Debug with undefined sanitize'
            build_type: 'debug'
            extra_args: '-Db_sanitize=undefined -Db_lundef=false'
            target: ${{ inputs.target }}
            buildDir: 'buildDirDebugUsan'

    name: ${{ matrix.config.name }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}-fibers-${{ matrix.config.buildDir }}
      - run: |
          python tools/configure.py
      - run: |
          meson setup --native-file ${{env.BuidlDir}}/conan_meson_native.ini ${{ matrix.config.buildDir }} . --buildtype ${{ matrix.config.build_type }} ${{ matrix.config.extra_args }}
          meson compile -C ${{ matrix.config.buildDir }} ${{ matrix.config.target }} test_${{ matrix.config.target }}
          ./${{ matrix.config.buildDir }}/test/${{ matrix.config.target }}/test_${{ matrix.config.target }} -print-errorlogs --verbose

#  release:
#    name: "debug-sanitize-release"
#    uses: ./actions/build/template.yaml
#    with:
#      build_type: 'release'
#      extra_args: ''
#      target: ${{ inputs.target }}