name: Template

on:
  workflow_call:
    inputs:
      build_type:
        description: 'The build type to use with Meson'
        required: true
        type: string
        default: 'release'
      extra_args:
        description: 'Extra arguments for Meson'
        required: false
        type: string
        default: ''
      target:
        description: 'Target for Meson'
        required: true
        type: string

env:
  BuidlDir: buildDir
  CC: /usr/bin/clang-18
  CXX: /usr/bin/clang++-18

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}-executor
      - run: |
          python tools/configure.py
      - run: |
          meson setup --native-file ${{env.BuidlDir}}/conan_meson_native.ini ${{env.BuidlDir}} . --buildtype ${{ inputs.build_type }} ${{ inputs.extra_args }}
          meson compile -C ${{env.BuidlDir}} ${{ inputs.target }} test_${{ inputs.target }}
          ./${{env.BuidlDir}}/test/${{ inputs.target }}/test_${{ inputs.target }} -print-errorlogs --verbose
